version: '3.3'

services:

   
    twitterfeedback:
        build: ./microservices/ri-collection-explicit-feedback-twitter
        ports: 
            - 9624:9624
        environment:
            - CONSUMER_KEY=rouiGCgbCWtW0JE9wCVzJtqWs
            - CONSUMER_SECRET=UP1pVOrbJZcs3MloIGtlBNA3RQSsHYG6WIE5O34Q5icUyy4qEM
            - ACCESS_KEY=1088353565293404160-a6dEctneMCumiafDWvEPybByMtKpJS
            - ACCESS_SECRET=tHzmjGvU5ijzy2HGr5kw390PJu5T1RvEffpY7d4UhiG0a
    storage:
        build: ./microservices/ri-storage-twitter
        ports:
            - 9682:9682
        environment:
            - MONGO_IP=193.146.116.148:27017
        depends_on:
            - mongodb
    
    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        volumes: 
            - "databaseEOCS:/data/db"
   
    classification:
        build: 
            context: ./microservices/ri-analytics-classification-twitter
            args: 
            - "GDRIVE_DL_LINK=1fcMjYmmjY9-WMOauYle6fFLooJ0u9OlU"
        ports: 
            - 9655:9655
        volumes:
            - "./microservices/ri-analytics-classification-twitter/SentiStrength.jar:/app/amazon-kinesis-client-python/sentistrength/SentiStrength.jar"
    orchestration:
        build: ./microservices/ri-orchestration-twitter
        ports: 
            - 9703:9703
        environment:
            - BASE_URL=http://193.146.116.148
        volumes: 
            - "./microservices/ri-orchestration-twitter/ca_chain.crt:/go/src/app/ca_chain.crt"
        depends_on:
            - twitterfeedback
            - storage
            - classification

    liquidedemocracy:
        build: ./microservices/gds-edemocracy
        ports:
          - "9750:9750"
        depends_on:
          - "db"
        environment:
          MIX_ENV: docker
          EXVOTE_PORT: 9750
          EXVOTE_PATH: /
          EXVOTE_HOST: localhost
    db:
        image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ex_vote_dev
        volumes:
          - "db-data:/var/lib/postgresql/data"


    frontend:    
        build: ./frontend
        ports:
            - 4200:4200
        depends_on:
            - backend
    backend:
        build: ./backend
        ports:
            - 3000:3000

volumes:
    db-data:
        #external : true
    databaseEOCS:

